--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NE-EIN-128-00
-- User name     : yves.meyer
-- Time stamp    : Tue Dec 02 10:53:15 2014
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.Address_Decode
-- Last modified : Tue Jul 08 12:25:20 2014.
--------------------------------------------------------------------------------



library Work, ieee;
use Work.nanoProcesseur_package.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_1164.all;

entity Address_Decode is
  port (
    addr_i      : in     std_logic_vector(7 downto 0);
    cs_port_a_o : out    std_logic;
    cs_port_b_o : out    std_logic;
    cs_ram_o    : out    std_logic);
end entity Address_Decode;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.Address_Decode.behavioral
-- Last modified : Tue Jul 08 12:25:20 2014.
--------------------------------------------------------------------------------


architecture behavioral of Address_Decode is

begin

cs_ram_o      <= '1' when addr_i(7 DOWNTO 5) = "000" else '0';

cs_port_a_o	<= '1' when addr_i(7 DOWNTO 5) = "100" and addr_i(0)= '0' else '0';
cs_port_b_o	<= '1' when addr_i(7 DOWNTO 5) = "100" and addr_i(0)= '1' else '0'; 


end architecture behavioral ; -- of Address_Decode

