--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NE-EIN-128-00
-- User name     : yves.meyer
-- Time stamp    : Tue Dec 02 10:53:15 2014
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.Instruction_Register
-- Last modified : Tue Jul 08 11:14:04 2014.
--------------------------------------------------------------------------------



library Work, ieee;
use Work.nanoProcesseur_package.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_1164.all;

entity Instruction_Register is
  port (
    clk_i      : in     std_logic;
    reset_i    : in     std_logic;
    IR_load_i  : in     std_logic;
    IR_i       : in     std_logic_vector(13 downto 0);
    operande_o : out    std_logic_vector(7 downto 0);
    opcode_o   : out    std_logic_vector(5 downto 0));
end entity Instruction_Register;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.Instruction_Register.Behavioral
-- Last modified : Tue Jul 08 11:14:04 2014.
--------------------------------------------------------------------------------

architecture Behavioral of Instruction_Register is
  
begin

process(clk_i,reset_i)
begin
  if reset_i = '0' then
    operande_o <= (others => '0');
    opcode_o <= (others => '0');
  elsif rising_edge(clk_i) then
    if IR_load_i = '1' then
      operande_o <= IR_i(7 DOWNTO 0);
      opcode_o <= IR_i(13 DOWNTO 8);
    end if;
  end if;
end process;

end architecture Behavioral ; -- of Instruction_Register
