--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NE-EIN-128-00
-- User name     : yves.meyer
-- Time stamp    : Tue Dec 02 10:53:15 2014
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.Program_Counter
-- Last modified : Tue Dec 02 10:48:19 2014.
--------------------------------------------------------------------------------



library Work, ieee;
use Work.nanoProcesseur_package.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_1164.all;

entity Program_Counter is
  port (
    clk_i     : in     std_logic;
    reset_i   : in     std_logic;
    PC_load_i : in     std_logic;
    PC_o      : out    std_logic_vector(7 downto 0);
    PC_inc_i  : in     std_logic;
    addr_i    : in     std_logic_vector(7 downto 0));
end entity Program_Counter;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.Program_Counter.Behavioral
-- Last modified : Tue Dec 02 10:48:19 2014.
--------------------------------------------------------------------------------

architecture Behavioral of Program_Counter is
    
 SIGNAL PC_counter : std_logic_vector(7 DOWNTO 0);
  
begin

process(clk_i,reset_i)
begin
  if reset_i = '0' then
    PC_counter <= (others => '0');
  elsif rising_edge(clk_i) then
    if PC_inc_i = '1' THEN
    	PC_counter <= UNSIGNED(PC_counter) + 1;
    elsif PC_load_i = '1' then
    	PC_counter <= addr_i;	  
    end if;
  end if;
end process;

PC_o <= PC_counter;

end architecture Behavioral ; -- of Program_Counter
