--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NE-EIN-128-00
-- User name     : yves.meyer
-- Time stamp    : Tue Dec 02 10:53:15 2014
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.W_Register
-- Last modified : Tue Jul 08 11:07:34 2014.
--------------------------------------------------------------------------------



library Work, ieee;
use Work.nanoProcesseur_package.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_1164.all;

entity W_Register is
  port (
    Accu_in     : in     std_logic_vector(7 downto 0);
    Accu_load_i : in     std_logic;
    Accu_o      : out    std_logic_vector(7 downto 0);
    clk_i       : in     std_logic;
    reset_i     : in     std_logic);
end entity W_Register;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.W_Register.Behavioral
-- Last modified : Tue Jul 08 11:07:34 2014.
--------------------------------------------------------------------------------


architecture Behavioral of W_Register is

begin

process(clk_i,reset_i)
begin
  if reset_i = '0' then
    Accu_o <= (others => '0');
  elsif rising_edge(clk_i) then
    if Accu_load_i = '1' then
      Accu_o <= Accu_in;
    end if;
  end if;
end process;

end architecture Behavioral ; -- of W_Register

